### ISSUE TITLE
os not defined in line 3 of run_retrieve_independent_blocks.py

### ISSUE THREAD

**Issue by biona001** [aaronsossin/gnomAD_LD_Easy_Querying#2]
Step 2 finished downloading. 

In step 3, it seems like `run_retrieve_independent_blocks.py` needs the following line to run
```python
import os
```

**Comment by aaronsossin** [comment]
Hi, thank you! Moved import os to top of file.

**Comment by biona001** [comment]
Note the `import os` line is also needed in `gnomAD_LD_Easy_Querying/generating_LD_matrices/run_populate_LD_matrices.py`
