### ISSUE TITLE
ModuleNotFoundError: No module named 'hail'

### ISSUE THREAD

**Issue by biona001** [aaronsossin/gnomAD_LD_Easy_Querying#3]
For step 3, I needed to install a python package `hail` via
```
pip3 install hail
```
Otherwise I get a `ModuleNotFoundError: No module named 'hail'` error in `gnomAD_LD_Easy_Querying/batch_script_files/error_files`

**Comment by aaronsossin** [comment]
Thank you for this comment! Forgot that this was part of environment setup. I am adding this to the README instructions to ensure that this is performed before subsequent operations

**Comment by biona001** [comment]
Note I also needed to install a few other libraries, such as `sklearn` and `matplotlib`
