### ISSUE TITLE
Did not get 22 files after running run_retrieve_independent_blocks.py

### ISSUE THREAD

**Issue by biona001** [aaronsossin/gnomAD_LD_Easy_Querying#5]
After I did 
```
python3 run_retrieve_independent_blocks.py afr
```
I did submit a bunch of jobs, all of which seemed to ran for at least a few minutes. However in `gnomAD_LD_Easy_Querying/independent_partitions/afr` I only have 1 file with name `partitions_for_<built-in function chr>.pickle`

Is this another file name issue?

**Comment by aaronsossin** [comment]
Thank you for the comment! There was a bug in that file that is now fixed. Please pull the most recent repo :)
